#!/bin/bash

compiz=`ps ax | grep 'compiz --replace' | grep -v 'grep' | awk '{print $5}'`

theme=`gsettings get org.mate.Marco.general theme | cut -d\' -f2`



if [ "$compiz" = "compiz" ] ; then
	gtk-window-decorator --replace --marco-theme "$theme" &
	echo "$compiz with GTK windows-decorator"
	echo "GTK theme is $theme"
	else
	exit 0
fi

exit 0

